### ISSUE TITLE
Event Stream (otherwise known as msgStream)

### ISSUE THREAD

**Issue by stelcheck** [mage/mage-sdk-cpp#19]
@ronkorving @MiLk What is the status on this? Would love to have something work with here... this would allow us to have the same kind of real-time notifications we have in our HTML apps.
- [ ] What should be the API?
- [ ] What should be the libraries we use (can we pull it off with STL?)

**Comment by ronkorving** [comment]
If it doesn't exist already, I think it should be possible to implement an EventEmitter API not too different from Node's. At the same time, as far as non-cpp goes, I can imagine particular development frameworks already provide a mechanism and it may be more natural to integrate into that.

**Comment by ronkorving** [comment]
A quick google search yielded the following by the way (which uses Boost):

https://github.com/jmoyers/EventEmitter

**Comment by stelcheck** [comment]
I am ideally trying to keep away from boost as a dependency or subdependency. If anything, I am getting the impression so far that STL C++11 might be good enough. However, I very much like that API for events.

Are there any ETA for having something to play with in MAGE? I will also need to integrate the transport protocol on that, and would very much like to be able to do so while the MAGE implementation is under way (or before if even possible).

**Comment by stelcheck** [comment]
This would be probably something I would favour if usable

https://github.com/RushPL/cpp-EventEmitter/
https://github.com/RushPL/cpp-EventEmitter/blob/master/example.cpp

**Comment by stelcheck** [comment]
Or even http://www.coderexception.com/C33zNuumPWyXiQJS/eventemitter-class-in-c-listener-and-emitter perhaps?

**Comment by ronkorving** [comment]
The last link doesn't actually carry any implementation.

The first is a big pile of ... well... I understand it's tricky to pull off an elegant implementation, but boy..
Actually, just realized there's a "sane" version of the codebase (not sure why or what), which looks a bit better.

**Comment by MiLk** [comment]
I don't understand why you want to use a new library to do this.
Implementing the observer pattern with the STL is quite simple.

MAGE exposes the `/msgstream` endpoint.
You have to:
- provide a `sessionKey` parameter: https://github.com/mage/mage-sdk-cpp/issues/19#issuecomment-49258229
- confirm the received message: https://github.com/Wizcorp/mage/blob/develop/lib/msgServer/msgStream.js#L255
- specify the transport (`longpolling`|`shortpolling`): https://github.com/Wizcorp/mage/blob/develop/lib/msgServer/msgStream.js#L265

**Comment by stelcheck** [comment]
That raises the question: should I simply code something against the existing messageStream? How hard would it be? Are there any protocol specs somewhere?

**Comment by stelcheck** [comment]
@ronkorving If that last question can be answered, I'd start working on it some time next week.

**Comment by ronkorving** [comment]
I can help you with that, but not in this issue (documentation on the protocol is lacking, and I would like to walk you through it). It should not be hard.

**Comment by stelcheck** [comment]
I would prefer if you took the time to document the msgStream protocol instead. That would make it easier for other people to understand as well, I think.

**Comment by ronkorving** [comment]
No problem.

**Comment by ronkorving** [comment]
https://github.com/Wizcorp/mage/pull/721 contains the documentation you need.

**Comment by stelcheck** [comment]
Closed through #26
