### ISSUE TITLE
Lint integration (was: tabs vs spaces)

### ISSUE THREAD

**Issue by MiLk** [mage/mage-sdk-cpp#2]
The file [src/exceptions.h](https://github.com/Wizcorp/mage-sdk-cpp/blob/develop/src/exceptions.h) contains tabs and spaces for indentation.

Please make sure all the files use only one of them.

People tends to follow the [Google C++ style guide](http://google-styleguide.googlecode.com/svn/trunk/cppguide.xml#Spaces_vs._Tabs).

**Comment by MiLk** [comment]
Same in [src/mage.h](https://github.com/Wizcorp/mage-sdk-cpp/blob/develop/src/mage.h#L13-L15)

**Comment by ronkorving** [comment]
We use jslint (well, jshint) on all our JavaScript. But I think lint originated in the C community. There's no reason not to apply some code style and sanity checks rigorously here, as we do in JS.

**Comment by stelcheck** [comment]
@ronkorving Feel free to PR a lint integration. I don't have the time to do this, personally.

@MiLk Could you show me where? I think I fixed that around the same time you made this issue, and I do not see where the spaces you mention are.

**Comment by ronkorving** [comment]
For starters, let me google that for you. Facebook made one aware of all the new language features, and called it Flint: https://github.com/facebook/flint
Blog post: https://code.facebook.com/posts/729709347050548/under-the-hood-building-and-open-sourcing-flint/

**Comment by MiLk** [comment]
Style seems ok now.

**Comment by MiLk** [comment]
cpplint was added with #21.

Can be closed.
